FROM python:3.9-alpine

# set the working directory in the container
WORKDIR /code

# copy the dependencies file to the working directory
COPY requirements.txt .

# install dependencies
RUN pip install -r requirements.txt

# copy the content of the local src directory to the working directory
COPY server.py .
COPY config.json .

# command to run on container start
CMD [ "python", "./server.py" ]
